#![cfg(target_os = "linux")]

use std::io::{Read, Write};
use std::net::{Ipv4Addr, TcpListener, TcpStream, UdpSocket};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::mpsc;
use std::time::Duration;

use foxprox_cli::forward_ipv4_udp_packet_once;
use foxprox_core::{
    DnsPolicy, Endpoint, HostnamePattern, PolicyConfig, PolicyEngine, PolicyRule, Protocol,
    RuleAction, SandboxId,
};
use foxprox_device::TunPacketIo;
use foxprox_dns::{handle_tun_dns_packet, DnsBrokerDatagramHandler, UdpDnsForwarder};
use foxprox_egress::{HostUdpEgress, UdpTarget};
use foxprox_inspect::DnsAttributionCache;
use foxprox_integrations::fd_handoff::BrokerControlListener;
use foxprox_tcp::SmoltcpTcpServer;

#[test]
#[ignore = "requires bwrap, /dev/net/tun, user namespaces, and Python in the sandbox"]
fn live_bwrap_foxproxsetup_hands_fd_and_exposes_target_udp_packet() {
    let Some(bwrap) = existing_path("/usr/bin/bwrap") else {
        eprintln!("skipping live smoke: /usr/bin/bwrap missing");
        return;
    };
    if !Path::new("/dev/net/tun").exists() {
        eprintln!("skipping live smoke: /dev/net/tun missing");
        return;
    }
    let Some(python) = existing_path("/usr/bin/python3") else {
        eprintln!("skipping live smoke: /usr/bin/python3 missing");
        return;
    };
    let setup = foxproxsetup_path();
    let dir = unique_test_dir("live-bwrap-setup");
    std::fs::create_dir_all(&dir).unwrap();
    let socket_path = dir.join("broker.sock");
    let resolv_conf = dir.join("resolv.conf");
    let listener = BrokerControlListener::bind(&socket_path).unwrap();
    let upstream = UdpSocket::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
    let upstream_addr = upstream.local_addr().unwrap();
    let upstream_thread = std::thread::spawn(move || {
        let mut buffer = [0_u8; 64];
        let (length, peer) = upstream.recv_from(&mut buffer).unwrap();
        assert_eq!(&buffer[..length], b"hi");
        upstream.send_to(b"ok", peer).unwrap();
    });
    let egress = HostUdpEgress::new(Duration::from_secs(3)).unwrap();
    let target = UdpTarget::new_ip(upstream_addr.ip(), upstream_addr.port()).unwrap();
    let (packet_tx, packet_rx) = mpsc::channel();

    let broker_thread = std::thread::spawn(move || {
        let received = listener.accept_setup_fd().unwrap();
        let mut tun = TunPacketIo::from_owned_fd(received.fd, 4096).unwrap();
        loop {
            let packet = tun.read_packet().unwrap();
            if let Ok(reply) = forward_ipv4_udp_packet_once(&packet, &egress, &target, 64) {
                tun.write_packet(&reply).unwrap();
                packet_tx.send(packet).unwrap();
                break;
            }
        }
    });

    let status = Command::new(bwrap)
        .args([
            "--unshare-user",
            "--unshare-net",
            "--cap-add",
            "CAP_NET_ADMIN",
            "--dev-bind",
            "/",
            "/",
            "--dev-bind",
            "/dev/net/tun",
            "/dev/net/tun",
        ])
        .arg(setup)
        .arg("--broker-socket")
        .arg(&socket_path)
        .args([
            "--tun-name",
            "fpxsmoke0",
            "--address-cidr",
            "10.126.0.2/24",
            "--mtu",
            "1400",
        ])
        .arg("--resolv-conf")
        .arg(&resolv_conf)
        .args(["--broker-dns", "10.126.0.1", "--ip-program", "/usr/bin/ip", "--"])
        .arg(python)
        .args([
            "-c",
            "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.settimeout(3); s.sendto(b'hi', ('10.126.0.1', 5353)); data, addr = s.recvfrom(16); assert data == b'ok', (data, addr)",
        ])
        .status()
        .unwrap();

    assert!(status.success(), "bwrap foxproxsetup exited with {status}");
    let packet = packet_rx
        .recv_timeout(Duration::from_secs(5))
        .expect("broker reads target-generated IPv4 packet from received TUN fd");
    broker_thread.join().unwrap();
    upstream_thread.join().unwrap();

    assert_eq!(packet[0] >> 4, 4);
    assert_eq!(packet[9], 17, "target packet should be UDP");
    assert_eq!(&packet[12..16], &[10, 126, 0, 2]);
    assert_eq!(&packet[16..20], &[10, 126, 0, 1]);
    assert!(packet.ends_with(b"hi"));
    assert_eq!(
        std::fs::read_to_string(&resolv_conf).unwrap(),
        "# generated by foxproxsetup\nnameserver 10.126.0.1\noptions ndots:0\n"
    );
    std::fs::remove_dir_all(dir).unwrap();
}

#[test]
#[ignore = "requires bwrap, /dev/net/tun, user namespaces, and Python in the sandbox"]
fn live_bwrap_dns_query_uses_tun_dns_handler_and_host_upstream() {
    let Some(bwrap) = existing_path("/usr/bin/bwrap") else {
        eprintln!("skipping live DNS smoke: /usr/bin/bwrap missing");
        return;
    };
    if !Path::new("/dev/net/tun").exists() {
        eprintln!("skipping live DNS smoke: /dev/net/tun missing");
        return;
    }
    let Some(python) = existing_path("/usr/bin/python3") else {
        eprintln!("skipping live DNS smoke: /usr/bin/python3 missing");
        return;
    };
    let setup = foxproxsetup_path();
    let dir = unique_test_dir("live-bwrap-dns");
    std::fs::create_dir_all(&dir).unwrap();
    let socket_path = dir.join("broker.sock");
    let resolv_conf = dir.join("resolv.conf");
    let listener = BrokerControlListener::bind(&socket_path).unwrap();
    let query = dns_a_query("dns.example.com");
    let response = dns_a_response(&query, [93, 184, 216, 34], 60);
    let upstream = UdpSocket::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
    let upstream_addr = upstream.local_addr().unwrap();
    let expected_query = query.clone();
    let upstream_thread = std::thread::spawn(move || {
        let mut buffer = [0_u8; 512];
        let (length, peer) = upstream.recv_from(&mut buffer).unwrap();
        assert_eq!(&buffer[..length], expected_query.as_slice());
        upstream.send_to(&response, peer).unwrap();
    });
    let (packet_tx, packet_rx) = mpsc::channel();
    let handler = DnsBrokerDatagramHandler::new(
        live_dns_policy(Endpoint::udp(Ipv4Addr::new(10, 127, 0, 1).into(), 53)),
        UdpDnsForwarder::new(UdpTarget::new_ip(upstream_addr.ip(), upstream_addr.port()).unwrap()),
        Endpoint::udp(Ipv4Addr::new(10, 127, 0, 1).into(), 53),
    );
    let egress = HostUdpEgress::new(Duration::from_secs(3)).unwrap();

    let broker_thread = std::thread::spawn(move || {
        let received = listener.accept_setup_fd().unwrap();
        let mut tun = TunPacketIo::from_owned_fd(received.fd, 4096).unwrap();
        let mut cache = DnsAttributionCache::new();
        loop {
            let packet = tun.read_packet().unwrap();
            if let Ok(result) = handle_tun_dns_packet(
                &packet,
                &handler,
                &egress,
                SandboxId::new("live-dns-smoke").unwrap(),
                &mut cache,
                std::time::SystemTime::UNIX_EPOCH,
            ) {
                if let Some(response_packet) = result.response_packet {
                    tun.write_packet(&response_packet).unwrap();
                    packet_tx.send(packet).unwrap();
                    break;
                }
            }
        }
    });
    let query_literal = python_bytes_literal(&query);
    let script = format!(
        "import socket; q={query_literal}; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.settimeout(3); s.sendto(q, ('10.127.0.1', 53)); data, addr = s.recvfrom(512); assert data[:2] == q[:2], data; assert data[3] & 15 == 0, data; assert data.endswith(bytes([93,184,216,34])), data"
    );

    let status = Command::new(bwrap)
        .args([
            "--unshare-user",
            "--unshare-net",
            "--cap-add",
            "CAP_NET_ADMIN",
            "--dev-bind",
            "/",
            "/",
            "--dev-bind",
            "/dev/net/tun",
            "/dev/net/tun",
        ])
        .arg(setup)
        .arg("--broker-socket")
        .arg(&socket_path)
        .args([
            "--tun-name",
            "fpxdns0",
            "--address-cidr",
            "10.127.0.2/24",
            "--mtu",
            "1400",
        ])
        .arg("--resolv-conf")
        .arg(&resolv_conf)
        .args([
            "--broker-dns",
            "10.127.0.1",
            "--ip-program",
            "/usr/bin/ip",
            "--",
        ])
        .arg(python)
        .args(["-c", &script])
        .status()
        .unwrap();

    assert!(status.success(), "bwrap DNS smoke exited with {status}");
    let packet = packet_rx
        .recv_timeout(Duration::from_secs(5))
        .expect("broker reads target DNS packet from received TUN fd");
    broker_thread.join().unwrap();
    upstream_thread.join().unwrap();

    assert_eq!(packet[0] >> 4, 4);
    assert_eq!(packet[9], 17);
    assert_eq!(&packet[12..16], &[10, 127, 0, 2]);
    assert_eq!(&packet[16..20], &[10, 127, 0, 1]);
    assert!(packet.ends_with(&query));
    std::fs::remove_dir_all(dir).unwrap();
}

#[test]
#[ignore = "requires bwrap, /dev/net/tun, user namespaces, and Python in the sandbox"]
fn live_bwrap_tcp_connection_uses_smoltcp_and_host_stream() {
    let Some(bwrap) = existing_path("/usr/bin/bwrap") else {
        eprintln!("skipping live TCP smoke: /usr/bin/bwrap missing");
        return;
    };
    if !Path::new("/dev/net/tun").exists() {
        eprintln!("skipping live TCP smoke: /dev/net/tun missing");
        return;
    }
    let Some(python) = existing_path("/usr/bin/python3") else {
        eprintln!("skipping live TCP smoke: /usr/bin/python3 missing");
        return;
    };
    let setup = foxproxsetup_path();
    let dir = unique_test_dir("live-bwrap-tcp");
    std::fs::create_dir_all(&dir).unwrap();
    let socket_path = dir.join("broker.sock");
    let resolv_conf = dir.join("resolv.conf");
    let listener = BrokerControlListener::bind(&socket_path).unwrap();
    let upstream = TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
    let upstream_addr = upstream.local_addr().unwrap();
    let upstream_thread = std::thread::spawn(move || {
        let (mut stream, _) = upstream.accept().unwrap();
        let mut buffer = [0_u8; 16];
        let length = stream.read(&mut buffer).unwrap();
        assert_eq!(&buffer[..length], b"hi");
        stream.write_all(b"ok").unwrap();
    });
    let (packet_tx, packet_rx) = mpsc::channel();

    let broker_thread = std::thread::spawn(move || {
        let received = listener.accept_setup_fd().unwrap();
        let mut tun = TunPacketIo::from_owned_fd(received.fd, 4096).unwrap();
        let mut tcp = SmoltcpTcpServer::new(Ipv4Addr::new(10, 129, 0, 1), 24, 8080, 1400);
        let mut host = TcpStream::connect(upstream_addr).unwrap();
        loop {
            let packet = tun.read_packet().unwrap();
            for outbound in tcp.accept_packet(packet.clone()) {
                tun.write_packet(&outbound).unwrap();
            }
            if tcp.can_recv() {
                let stats = tcp.relay_once(&mut host, 64, 64).unwrap();
                for outbound in tcp.poll() {
                    tun.write_packet(&outbound).unwrap();
                }
                packet_tx.send((packet, stats)).unwrap();
                break;
            }
        }
    });
    let status = Command::new(bwrap)
        .args([
            "--unshare-user",
            "--unshare-net",
            "--cap-add",
            "CAP_NET_ADMIN",
            "--dev-bind",
            "/",
            "/",
            "--dev-bind",
            "/dev/net/tun",
            "/dev/net/tun",
        ])
        .arg(setup)
        .arg("--broker-socket")
        .arg(&socket_path)
        .args([
            "--tun-name",
            "fpxtcp0",
            "--address-cidr",
            "10.129.0.2/24",
            "--mtu",
            "1400",
        ])
        .arg("--resolv-conf")
        .arg(&resolv_conf)
        .args([
            "--broker-dns",
            "10.129.0.1",
            "--ip-program",
            "/usr/bin/ip",
            "--",
        ])
        .arg(python)
        .args([
            "-c",
            "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(5); s.connect(('10.129.0.1', 8080)); s.sendall(b'hi'); data=s.recv(16); assert data == b'ok', data",
        ])
        .status()
        .unwrap();

    assert!(status.success(), "bwrap TCP smoke exited with {status}");
    let (packet, stats) = packet_rx
        .recv_timeout(Duration::from_secs(5))
        .expect("broker relays live TCP payload through smoltcp");
    broker_thread.join().unwrap();
    upstream_thread.join().unwrap();

    assert_eq!(packet[0] >> 4, 4);
    assert_eq!(packet[9], 6);
    assert_eq!(stats.sandbox_to_host_bytes, 2);
    assert_eq!(stats.host_to_sandbox_bytes, 2);
    std::fs::remove_dir_all(dir).unwrap();
}

fn dns_a_query(hostname: &str) -> Vec<u8> {
    let mut query = vec![
        0x12, 0x34, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
    for label in hostname.split('.') {
        query.push(label.len() as u8);
        query.extend_from_slice(label.as_bytes());
    }
    query.push(0);
    query.extend_from_slice(&1_u16.to_be_bytes());
    query.extend_from_slice(&1_u16.to_be_bytes());
    query
}

fn dns_a_response(query: &[u8], address: [u8; 4], ttl_seconds: u32) -> Vec<u8> {
    let mut response = query.to_vec();
    response[2] = 0x81;
    response[3] = 0x80;
    response[6] = 0x00;
    response[7] = 0x01;
    response.extend_from_slice(&0xc00c_u16.to_be_bytes());
    response.extend_from_slice(&1_u16.to_be_bytes());
    response.extend_from_slice(&1_u16.to_be_bytes());
    response.extend_from_slice(&ttl_seconds.to_be_bytes());
    response.extend_from_slice(&4_u16.to_be_bytes());
    response.extend_from_slice(&address);
    response
}

fn live_dns_policy(resolver: Endpoint) -> PolicyEngine {
    let rule = PolicyRule::new("allow-live-dns", RuleAction::Allow)
        .unwrap()
        .with_protocol(Protocol::Dns)
        .with_hostname(HostnamePattern::new(".example.com").unwrap())
        .with_destination_port(53);
    PolicyEngine::new(PolicyConfig {
        dns: DnsPolicy {
            broker_resolvers: vec![resolver],
            deny_direct_external_dns: true,
        },
        rules: vec![rule],
        ..PolicyConfig::default()
    })
}

fn python_bytes_literal(bytes: &[u8]) -> String {
    let escaped = bytes
        .iter()
        .map(|byte| format!("\\x{byte:02x}"))
        .collect::<String>();
    format!("b'{escaped}'")
}

fn existing_path(path: &str) -> Option<PathBuf> {
    let path = PathBuf::from(path);
    path.exists().then_some(path)
}

fn foxproxsetup_path() -> PathBuf {
    std::env::var_os("CARGO_BIN_EXE_foxproxsetup")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/debug/foxproxsetup"))
}

fn unique_test_dir(prefix: &str) -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    std::env::temp_dir().join(format!(
        "foxprox-cli-{prefix}-{}-{nanos}",
        std::process::id()
    ))
}
