#![cfg(target_os = "linux")]

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::mpsc;
use std::time::Duration;

use foxprox_device::TunPacketIo;
use foxprox_integrations::fd_handoff::BrokerControlListener;

#[test]
#[ignore = "requires bwrap, /dev/net/tun, user namespaces, and Python in the sandbox"]
fn live_bwrap_foxproxsetup_hands_fd_and_exposes_target_udp_packet() {
    let Some(bwrap) = existing_path("/usr/bin/bwrap") else {
        eprintln!("skipping live smoke: /usr/bin/bwrap missing");
        return;
    };
    if !Path::new("/dev/net/tun").exists() {
        eprintln!("skipping live smoke: /dev/net/tun missing");
        return;
    }
    let Some(python) = existing_path("/usr/bin/python3") else {
        eprintln!("skipping live smoke: /usr/bin/python3 missing");
        return;
    };
    let setup = foxproxsetup_path();
    let dir = unique_test_dir("live-bwrap-setup");
    std::fs::create_dir_all(&dir).unwrap();
    let socket_path = dir.join("broker.sock");
    let resolv_conf = dir.join("resolv.conf");
    let listener = BrokerControlListener::bind(&socket_path).unwrap();
    let (packet_tx, packet_rx) = mpsc::channel();

    let broker_thread = std::thread::spawn(move || {
        let received = listener.accept_setup_fd().unwrap();
        let mut tun = TunPacketIo::from_owned_fd(received.fd, 4096).unwrap();
        loop {
            let packet = tun.read_packet().unwrap();
            if let Some(reply) = ipv4_udp_reply(&packet, b"ok") {
                tun.write_packet(&reply).unwrap();
                packet_tx.send(packet).unwrap();
                break;
            }
        }
    });

    let status = Command::new(bwrap)
        .args([
            "--unshare-user",
            "--unshare-net",
            "--cap-add",
            "CAP_NET_ADMIN",
            "--dev-bind",
            "/",
            "/",
            "--dev-bind",
            "/dev/net/tun",
            "/dev/net/tun",
        ])
        .arg(setup)
        .arg("--broker-socket")
        .arg(&socket_path)
        .args([
            "--tun-name",
            "fpxsmoke0",
            "--address-cidr",
            "10.126.0.2/24",
            "--mtu",
            "1400",
        ])
        .arg("--resolv-conf")
        .arg(&resolv_conf)
        .args(["--broker-dns", "10.126.0.1", "--ip-program", "/usr/bin/ip", "--"])
        .arg(python)
        .args([
            "-c",
            "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM); s.settimeout(3); s.sendto(b'hi', ('10.126.0.1', 5353)); data, addr = s.recvfrom(16); assert data == b'ok', (data, addr)",
        ])
        .status()
        .unwrap();

    assert!(status.success(), "bwrap foxproxsetup exited with {status}");
    let packet = packet_rx
        .recv_timeout(Duration::from_secs(5))
        .expect("broker reads target-generated IPv4 packet from received TUN fd");
    broker_thread.join().unwrap();

    assert_eq!(packet[0] >> 4, 4);
    assert_eq!(packet[9], 17, "target packet should be UDP");
    assert_eq!(&packet[12..16], &[10, 126, 0, 2]);
    assert_eq!(&packet[16..20], &[10, 126, 0, 1]);
    assert!(packet.ends_with(b"hi"));
    assert_eq!(
        std::fs::read_to_string(&resolv_conf).unwrap(),
        "# generated by foxproxsetup\nnameserver 10.126.0.1\noptions ndots:0\n"
    );
    std::fs::remove_dir_all(dir).unwrap();
}

fn ipv4_udp_reply(request: &[u8], payload: &[u8]) -> Option<Vec<u8>> {
    if request.len() < 28 || request[0] >> 4 != 4 || request[9] != 17 {
        return None;
    }
    let ihl = usize::from(request[0] & 0x0f) * 4;
    if ihl < 20 || request.len() < ihl + 8 {
        return None;
    }
    let udp_len = u16::from_be_bytes([request[ihl + 4], request[ihl + 5]]) as usize;
    if udp_len < 8 || request.len() < ihl + udp_len {
        return None;
    }

    let total_len = 20 + 8 + payload.len();
    let mut reply = vec![0_u8; total_len];
    reply[0] = 0x45;
    reply[2..4].copy_from_slice(&(total_len as u16).to_be_bytes());
    reply[6..8].copy_from_slice(&0x4000_u16.to_be_bytes());
    reply[8] = 64;
    reply[9] = 17;
    reply[12..16].copy_from_slice(&request[16..20]);
    reply[16..20].copy_from_slice(&request[12..16]);
    let checksum = ipv4_header_checksum(&reply[..20]);
    reply[10..12].copy_from_slice(&checksum.to_be_bytes());

    reply[20..22].copy_from_slice(&request[ihl + 2..ihl + 4]);
    reply[22..24].copy_from_slice(&request[ihl..ihl + 2]);
    reply[24..26].copy_from_slice(&((8 + payload.len()) as u16).to_be_bytes());
    reply[26..28].copy_from_slice(&0_u16.to_be_bytes());
    reply[28..].copy_from_slice(payload);
    Some(reply)
}

fn ipv4_header_checksum(header: &[u8]) -> u16 {
    let mut sum = 0_u32;
    for chunk in header.chunks_exact(2) {
        sum += u32::from(u16::from_be_bytes([chunk[0], chunk[1]]));
    }
    while (sum >> 16) != 0 {
        sum = (sum & 0xffff) + (sum >> 16);
    }
    !(sum as u16)
}

fn existing_path(path: &str) -> Option<PathBuf> {
    let path = PathBuf::from(path);
    path.exists().then_some(path)
}

fn foxproxsetup_path() -> PathBuf {
    std::env::var_os("CARGO_BIN_EXE_foxproxsetup")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("target/debug/foxproxsetup"))
}

fn unique_test_dir(prefix: &str) -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    std::env::temp_dir().join(format!(
        "foxprox-cli-{prefix}-{}-{nanos}",
        std::process::id()
    ))
}
