[workspace]
exclude = ["fuzz"]
members = [
    "crates/foxprox-audit",
    "crates/foxprox-cli",
    "crates/foxprox-config",
    "crates/foxprox-core",
    "crates/foxprox-device",
    "crates/foxprox-dns",
    "crates/foxprox-egress",
    "crates/foxprox-frontends",
    "crates/foxprox-inspect",
    "crates/foxprox-integrations",
    "crates/foxprox-net",
    "crates/foxprox-packet",
    "crates/foxprox-policy",
    "crates/foxprox-runtime",
    "crates/foxprox-smoltcp",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foxfirecodes/foxprox"
rust-version = "1.80"
