[package]
name = "foxprox-net"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
foxprox-device = { path = "../foxprox-device" }
libc = "0.2"
smoltcp = { version = "0.12", default-features = false, features = ["std", "medium-ip", "proto-ipv4", "socket-tcp", "socket-udp"] }

[dev-dependencies]
foxprox-core = { path = "../foxprox-core" }
