[package]
name = "foxprox-egress"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
foxprox-core = { path = "../foxprox-core" }
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }

[dev-dependencies]
foxprox-device = { path = "../foxprox-device" }
foxprox-stack = { path = "../foxprox-stack" }

[lib]
path = "src/lib.rs"
