[package]
name = "foxprox-device"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
foxprox-core = { path = "../foxprox-core" }

[target.'cfg(unix)'.dependencies]
unix-ancillary = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
tun-rs = "2.8"

[dev-dependencies]
pretty_assertions = "1"

[lib]
path = "src/lib.rs"
